### PR TITLE
Updates for new infrastructure

### PR DESCRIPTION
**Pull request by hakbailey**
#### What does this PR do?
Minor changes (mostly documentation) necessary to move this app to the new AWS organization.

#### Includes new or updated dependencies?
YES

#### Developer
- [x] README is updated to reflect all changes as needed
- [x] All related Jira tickets are linked in commit message(s)

#### Code Reviewer
- [x] The commit message is clear and follows our guidelines (not just this pull request message)
- [ ] There are appropriate tests covering any new functionality
- [x] The documentation has been updated to reflect all changes or is not needed
- [ ] The changes have been verified
- [x] New dependencies are appropriate or there were no changes

### CODE REVIEW

**Comment by cabutlermit** [comment]
@hakbailey this might be a dumb question: now that you have added the `wheel` command to the `deps` command in the Makefile, shouldn't we also clean up the `PREBUILD:` line in the GHA workflows for `dev` and `stage`? 

Right now, those "Prebuild" commands include both `make deps` and `make wheel`, but that feels redundant.

**Comment by hakbailey** [comment]
> @hakbailey this might be a dumb question: now that you have added the `wheel` command to the `deps` command in the Makefile, shouldn't we also clean up the `PREBUILD:` line in the GHA workflows for `dev` and `stage`?
> 
> Right now, those "Prebuild" commands include both `make deps` and `make wheel`, but that feels redundant.

Yes, good catch! I'll update that.

**Comment by hakbailey** [comment]
@cabutlermit workflows updated!

**Comment by cabutlermit** [comment]
> @cabutlermit workflows updated!

@hakbailey  Looks good and the Dev Build action ran smoothly after removing the `make wheel` too. I'm going to wait until after the PR for the infrastructure is approved, merged, and deployed to Stage-Workloads before I officially approve this PR.

**Review by cabutlermit — APPROVED** [review]
Looks good. The infrastructure updates were merged and deployed to Stage-Workloads.

**Pull request merged**
